version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-and-test:
    docker:
      - image: node:16.13.2
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

workflows:
  build-and-test:
    jobs:
      - build-and-test
